# Por tema de pruebas decidi usar stdout para mostrar en la
# consola que se esta haciendo correctamente el registro de la bitacora.
log4j.rootLogger=ERROR, file, email, stdout  

log4j.appender.file=org.apache.log4j.RollingFileAppender  
log4j.appender.file.File=./logs/bitacoraCOIL.log
log4j.appender.file.MaxFileSize=4MB  
log4j.appender.file.MaxBackupIndex=10  
log4j.appender.file.layout=org.apache.log4j.PatternLayout  
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n  

# configuracion del appender para enviar correos electronicos (SMTP)
log4j.appender.email=org.apache.log4j.net.SMTPAppender
log4j.appender.email.SMTPProtocol=smtps
log4j.appender.email.SMTPPort=465
log4j.appender.email.SMTPHost=smtp.gmail.com
log4j.appender.email.SMTPUsername=maryek360@gmail.com
log4j.appender.email.SMTPPassword=loizpyqskpsdlgit
log4j.appender.email.From=maryek360@gmail.com
log4j.appender.email.To=ferram200011@gmail.com
log4j.appender.email.Subject=BitacoraRecursos de Sistema COIL
log4j.appender.email.BufferSize=1
log4j.appender.email.EvaluatorClass=BitacoraRecursos.TriggerLogEvent
log4j.appender.email.layout=org.apache.log4j.PatternLayout
log4j.appender.email.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
#todo como puedo manejar una excepcion si es que se va el internet???



# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender  
log4j.appender.stdout.Target=System.out  
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout  
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n  